### ISSUE TITLE
new triagens Namespace 'ArangoDBClient'

### ISSUE THREAD

**Issue by danielemay** [DevGroup-ru/yii2-arangodb#12]
With release of latest triagens/arangodb ( 3.2.4 ) I had an issue with namespacing inside devgroup/yii2-arangodb

to solve is needed to change arango class namespasces from `triagens\ArangoDb` to `ArangoDBClient`

example:
`use triagens\ArangoDb\Document;`
become:
`use ArangoDBClient\Document;`

**Comment by bethrezen** [comment]
Sorry, but this extension doesn't support new version of arango. We don't have time for supporting it.
If you can - please send us Pull Request
